theme: readthedocs
site_name: Molo Documentation
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation: installation.md
  - Functions: api.md
  - Basic Pipeline: basic_pipeline.md
  - Web Page: web.md
  - FAQ: FAQ.md